### ISSUE TITLE
UX Overhaul for entity management

### ISSUE THREAD

**Issue by havok2905** [havok2905/dm-screen#197]
Labeling is confusing for lists of markdown entity rows and their actions.

Changing content on a Markdown entity is split into five actions:

- Create the entity with minimal data
- Review the entity
- Attach other resources to entity
- Edit content on an entity directly
- Delete the entity

Right now there are three actions on the row:

- View
- Edit
- Destroy

These don't reflect how this data is actually worked with.

**Tasks**

- [x] 1. Move attachment of resources and images to the edit page
- [x] 2. Update Cypress tests to match the UI change
- [x] 3. Change labels to; Review, Manage, Delete
- [x] 4. Remove metadata creation on entity creation and use the default minimum
- [x] 5. Remove markdown creation on entity creation and default to templated string

**New Workflow**

1. Create new entity with name
2. Navigate to edit page for that item
3. Fill out metadata
4. Fill out markdown data
5. Attach images
6. Navigate to view page on save
7. Navigate to entities list to see the item in the list
